### ISSUE TITLE
Failed test 'Perinci/CmdLine/Util/Config.pm loaded ok'

### ISSUE THREAD

**Issue by nanis** [perlancar/perl-Perinci-CmdLine-Lite#1]
Failure to load Perinci::CmdLine::Util::Config causes further test failures down the line.

This module has

    use PERLANCAR::File::HomeDir qw(get_my_home_dir);

I am not sure what you intended to do here.

**Comment by nanis** [comment]
<pre>--> Working on PERLANCAR::File::HomeDir
Fetching http://www.cpan.org/authors/id/P/PE/PERLANCAR/PERLANCAR-File-HomeDir-0.01.tar.gz ... OK
Configuring PERLANCAR-File-HomeDir-0.01 ... OK
Building and testing PERLANCAR-File-HomeDir-0.01 ... OK
Successfully installed PERLANCAR-File-HomeDir-0.01
1 distribution installed</pre>

However:

<pre>t\run.t ................... 7/?
        #   Failed test 'output_re'
        #   at C:\Users\sinan\.cpanm\work\1427894848.5188\Perinci-CmdLine-Lite-1.03\blib\lib/Test/Perinci/CmdLine.pm line 70.
        #                   'ERROR 500: Died: The getpwuid function is unimplemented at C:/opt/perl-5.20.2/site/lib/PERLANCAR/File/HomeDir.pm line 28.
        # '
        #     doesn't match '(?^:^101$)'
        # output is <ERROR 500: Died: The getpwuid function is unimplemented at C:/opt/perl-5.20.2/site/lib/PERLANCAR/File/HomeDir.pm line 28.
        # >
        # Looks like you failed 1 test of 2.

    #   Failed test 'test_run: --config-path'
    #   at C:\Users\sinan\.cpanm\work\1427894848.5188\Perinci-CmdLine-Lite-1.03\blib\lib/Test/Perinci/CmdLine.pm line 77.
    # Looks like you failed 1 test of 11.

#   Failed test 'config'
#   at t\run.t line 881.</pre>

Which is related to https://github.com/perlancar/perl-Complete-Bash/issues/1 I believe.

**Comment by perlancar** [comment]
Sorry for the very late response, missed this PR/issue (didn't receive notification from GitHub).

This is now fixed, I just tested Perinci-CmdLine-Lite-1.61 under XP + Strawberry Perl 5.24.0.1
