### ISSUE TITLE
Question about Data::Clean::JSON (DEPRECATED)

### ISSUE THREAD

**Issue by bokutin** [perlancar/perl-Perinci-CmdLine-Lite#12]
Hello.

I'm trying to create a port for freebsd.

The dependent module Data::Clean::JSON is deprecated, are there any plans to change it to Data::Clean::ForJSON?

I'm hesitant to PR a new port for a module marked DEPRECATED.

Thanks,

**Comment by perlancar** [comment]
Sorry for the late response, didn't see the notification.

Changed in a9460e9
